---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: egs-cellwatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: registry.deti/cellwatch/notification_service:v4
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8500
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: egs-cellwatch
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
